name: CI
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    permissions: write-all # TODO: make this as strict as possible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run labeller
        id: labeller
        run: |
          git fetch --unshallow --tags
          GIT_DESCRIPTOR=$(git describe --tags --always --exclude latest --exclude unreleased)
          echo Detected descriptor: ${GIT_DESCRIPTOR}
          echo "VERSION=${GIT_DESCRIPTOR#v}" >> $GITHUB_OUTPUT
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Test
        run: |
          echo TODO
      - name: Build
        env:
          BASE_NAME: big-dict-${{ steps.labeller.outputs.version }}
        run: |
          deno task build --target=x86_64-unknown-linux-gnu
          tar --remove-files -czpf ${{ env.BASE_NAME }}-x86_64-lnx.tgz big-dict
          deno task build --target=x86_64-apple-darwin
          tar --remove-files -czpf ${{ env.BASE_NAME }}-x86_64-osx.tgz big-dict
          deno task build --target=aarch64-apple-darwin
          tar --remove-files -czpf ${{ env.BASE_NAME }}-arm_64-osx.tgz big-dict
          deno task build --target=x86_64-pc-windows-msvc
          zip -m9 ${{ env.BASE_NAME }}-x86_64-win big-dict.exe
      - name: "GitHub: update pre-release"
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.labeller.outputs.version }}
          UNRELEASED: update
          UNRELEASED_TAG: unreleased
          PRE_RELEASE: true
          DRAFT_RELEASE: false
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: |
            big-dict-${{ steps.labeller.outputs.version }}-*
      - name: "GitHub: delete pre-release"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNRELEASED: delete
          UNRELEASED_TAG: unreleased
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: |
            big-dict-${{ steps.labeller.outputs.version }}-*
      - name: "GitHub: create release"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.labeller.outputs.version }}
        with:
          args: |
            big-dict-${{ steps.labeller.outputs.version }}-*
